### ISSUE TITLE
这个是什么情况，下载一直被中断

### ISSUE THREAD

**Issue by cy920820** [orestonce/m3u8d#12]
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/21211512/194768999-39513679-bfc6-4b4a-8402-f9b1bc9143ee.png">

**Comment by cy920820** [comment]
是线程的问题吗？

**Comment by cy920820** [comment]
这个版本是？

**Comment by orestonce** [comment]
这个版本只有一个线程在下载，可以确定一下是不是下载线程太多造成的问题

**Comment by cy920820** [comment]
> 这个版本只有一个线程在下载，可以确定一下是不是下载线程太多造成的问题
好的，我测试完结果告诉你

**Comment by orestonce** [comment]
最新版本已支持选择单线程下载。
