### ISSUE TITLE
Macos下完的ts文件合并mp4失败

### ISSUE THREAD

**Issue by jiangslee** [orestonce/m3u8d#13]
最新版的命令行支持单独合并ts文件了

_Originally posted by @orestonce in https://github.com/orestonce/m3u8d/issues/5#issuecomment-1209363716_
      

[v1.15.20](https://github.com/orestonce/m3u8d/tree/v1.15.20) macos-qt版下载完成后目录里有一个`all.merge.mp4`，只有48字节

![image](https://user-images.githubusercontent.com/27892476/196333894-7f1e56cd-b83b-4510-a6ff-7d6f11483f5e.png)

![image](https://user-images.githubusercontent.com/27892476/196333867-43aeb811-bb0f-4650-8e85-58a2fd8acd1d.png)

补充：使用cli也有报错
```shell
./m3u8d merge --InputTsDir ./downloading/4a425bcbfa3b211254c58770cf6937eefe9ae8a66027afd2ecad4da87992f7a5                               
2022/10/18 12:23:20 合并失败 ts packet must start with 0x47
```
![image](https://user-images.githubusercontent.com/27892476/196335225-185bc9f6-3fa1-4d8d-a257-e87a46568b49.png)

**Comment by orestonce** [comment]
可能不是00001.ts，是其他ts。可以先使用二分法确定一下是哪个ts有问题。如果你不能确定，可以把 4a425bcbfa3b211254c58770cf6937eefe9ae8a66027afd2ecad4da87992f7a5 目录共享一下。

**Comment by jiangslee** [comment]
> 可能不是00001.ts，是其他ts。可以先使用二分法确定一下是哪个ts有问题。如果你不能确定，可以把 4a425bcbfa3b211254c58770cf6937eefe9ae8a66027afd2ecad4da87992f7a5 目录共享一下。

我用命令`cat *.ts > all.ts`后再用`ffmpeg -i all.ts -c copy -y all.mp4`，能手动合并成功。

**Comment by jiangslee** [comment]
确定是这个00001.ts导致的，我把这个文件单独放到另一个文件夹，跑merge命令也是一样的报错
```shell
~/Downloads$ ./m3u8d merge --InputTsDir ./downloading/test                                                                                           
2022/10/18 12:33:08 合并失败 ts packet must start with 0x47

 ~/Downloads$ tree downloading/test                                                                                                              1 ↵  
downloading/test
├── 00001.ts
└── all.mp4
```

**Comment by jiangslee** [comment]
[00001.ts.zip](https://github.com/orestonce/m3u8d/files/9806489/00001.ts.zip)

**Comment by orestonce** [comment]
最新版已解决
