### ISSUE TITLE
crypto/aes: invalid key size 9

### ISSUE THREAD

**Issue by benx1n** [orestonce/m3u8d#20]
m3u8链接是这个，我抹去了其中的session_id和media_view_id：[m3u8链接](https://hls-auth.cloud.stream.co.jp/mediaplaylist/smzhsFyhxSw2XZCpcFVkDKCJ/transcoded/7oohdvgunb5kj8d9_ldy856w0go0x2j4r_f4bGpcCPMpVnzF7HoFtgym_1_20230524-22-55-36_0_720p.m3u8?session_id=123&media_view_id=123)
原视频地址是这里：[链接](https://nicochannel.jp/piyopiyohiyona/video/smzhsFyhxSw2XZCpcFVkDKCJ)
m3u8文件中是存在以下AES-128的key信息
`#EXT-X-KEY:METHOD=AES-128,URI="https://hls-auth.cloud.stream.co.jp/key?session_id=123&123"`
（与上方m3u8中的session_id，media_view_id相同）
如果手动下载key后是可以通过这个项目正确下载TS[nilaoda/N_m3u8DL-CLI](https://github.com/nilaoda/N_m3u8DL-CLI)
但在m3u8d中报了invalid key size 9的错误
如果需要提供详细的session_id和media_view_id可以通过邮件发给您

**Comment by orestonce** [comment]
收到。请将详细的 session_id 和 media_view_id发我一下 `orestonce#163.com`

**Comment by orestonce** [comment]
收到

**Comment by orestonce** [comment]
可能是session_id 或者 media_view_id 映射过UA信息之类的，具体实现取决于网站的服务端作者。

**Comment by benx1n** [comment]
ok成功解决了，感谢您的解答

**Comment by yapingcat** [comment]
@benx1n  hello, hls流是你们自己生成的吗

**Comment by benx1n** [comment]
> @benx1n hello, hls流是你们自己生成的吗

是直接在页面上抓到的

**Comment by yapingcat** [comment]
应该是ts文件解密出问题了
我这边手动解密ts文件，解密出来的ts文件是有pat表的

````golang
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"fmt"
	"io/ioutil"
)

func main() {
	ts, e := ioutil.ReadFile("test.ts")
	b, e := ioutil.ReadFile("key")
	fmt.Println("%x", b, len(b), e)
	block, err := aes.NewCipher(b)
	if err != nil {
		fmt.Println(err)
	}
	iv := make([]byte, 16)
	iv[15] = 1
	blockMode := cipher.NewCBCDecrypter(block, iv)
	result := make([]byte, len(ts))
	blockMode.CryptBlocks(result, ts)
	unPadding := int(result[len(result)-1])
	result = result[:len(result)-unPadding]
	ioutil.WriteFile("d_test.ts", result, 0666)
}

````

解密后的ts文件
[d_test.zip](https://github.com/orestonce/m3u8d/files/11627127/d_test.zip)

**Comment by yapingcat** [comment]
https://datatracker.ietf.org/doc/html/rfc8216#section-5.2

>   An EXT-X-KEY tag with a KEYFORMAT of "identity" that does not have an
>    IV attribute indicates that the **Media Sequence Number is to be used**
>    as the IV when decrypting a Media Segment, by putting its big-endian
>    binary representation into a 16-octet (128-bit) buffer and padding
>    (on the left) with zeros.

看了 m3u8 文件里面 没有IV ，按照协议需要使用Media Sequence Number

看了代码，实现可能有点问题？？

**Comment by orestonce** [comment]
@yapingcat 你说得对，此处是一个bug

**Comment by orestonce** [comment]
@benx1n 改了，试一下最新版本

**Comment by benx1n** [comment]
没问题了，可以成功转码成mp4
