### ISSUE TITLE
能否增加为 go sdk模式

### ISSUE THREAD

**Issue by lavyw** [orestonce/m3u8d#21]
是否可以考虑增加一个 sdk 模式，可以集成到用户自己的 golang 代码里面调用

**Comment by orestonce** [comment]
目前没想好怎么提供api，提供哪些api

**Comment by yuzhiyizhan** [comment]
添加api能并发吗

**Comment by orestonce** [comment]
> 添加api能并发吗

可以

**Comment by orestonce** [comment]
好的，最近抽空加一下

**Comment by yuzhiyizhan** [comment]
> 好的，最近抽空加一下

感谢感谢

**Comment by orestonce** [comment]
@lavyw @yuzhiyizhan 最新代码已支持多实例模式，使用方法见 m3u8dcpp/download.go
