### ISSUE TITLE
怎么执行下载呢

### ISSUE THREAD

**Issue by beclass** [orestonce/m3u8d#22]
<img width="455" alt="image" src="https://github.com/orestonce/m3u8d/assets/12541388/01c62e9b-b4f8-448c-ae8c-7afd7ec1fa65">

**Comment by orestonce** [comment]
先执行 chmod +x test

**Comment by orestonce** [comment]
mac也有qt版本的ui [m3u8d_qt_darwin_amd64-v1.18.0.dmg](https://github.com/orestonce/m3u8d/releases/download/v1.18.0/m3u8d_qt_darwin_amd64-v1.18.0.dmg)

**Comment by beclass** [comment]
还是不行，我用qt版啦
<img width="1048" alt="image" src="https://github.com/orestonce/m3u8d/assets/12541388/4666da6e-d4c2-4161-bb20-0d4d7af58f5c">

**Comment by orestonce** [comment]
那就是 test 的编译过程不对:
````bash
cd cmd
go mod tidy
go build
chmod +x ./cmd
./cmd download ...
````

**Comment by beclass** [comment]
可以了，谢谢🙏
