### ISSUE TITLE
resp.Status: 428 是什么问题呢？

### ISSUE THREAD

**Issue by 1715819** [orestonce/m3u8d#23]
版本：m3u8d_cli_linux_386-v1.18.0
下载ts文件错误: resp.Status: 428  https://ao-block-ater.mushroomtrack.com/bcdn_token=hMqxqxayxs2V4sMuNEFrhbzJBhfUrlcw-Nq3DiivCNE&expires=1688549817&token_path=%2Fvod%2F/vod/8000/8125/8125713.ts

**Comment by orestonce** [comment]
有m3u8的链接没？
