### ISSUE TITLE
[feature] support H265 video format

### ISSUE THREAD

**Issue by superwushu** [orestonce/m3u8d#31]
Hey I got an error "unknown cid 36" when merging. It seems cid 36 == H265 as defined in `gomedia`:

```go
TS_STREAM_H265 TS_STREAM_TYPE = 0x24
```

Thanks in advance for adding this feature.

**Comment by orestonce** [comment]
The latest version([v1.24.1](https://github.com/orestonce/m3u8d/releases/tag/v1.24.1)) has supported H265，please try again.

**Comment by superwushu** [comment]
> The latest version([v1.24.1](https://github.com/orestonce/m3u8d/releases/tag/v1.24.1)) has supported H265，please try again.

Thank you for the quick fix! Unfortunately, tried on [this m3u8](https://ltshwy.gtimg.com/B_JxNyiJmktHRgresXhfyMehUCAIClAeds5JvPVluz1qbTUiK6SrueHWAxp0JqoXDy/Axjaqr0MPnIOsrl0FqhbJ7kk202p_yqBpMIpibFZ1EmOK1uj4yjtpTXCrKO5S_Jcm1fip7tJhvRhJ5KO8tdv-xhJ5S511waMxVjHbov5Q76mdMI9NpxUahHuR0zRXvjsC-AxN7zD_oeSVGk-0AV4Phrgr5fwr7TPhj8Sgg_RJ5qyrK8PWWdYz0qIBQzxy8ZVBpkMWydzBUmeBfpjQ_E2mYUIi3tfQbvYgtZHQJSHTJA/z0392sgue1o.322013.ts.m3u8?ver=4) but the merged file (mp4) is audio only. Without merging, all TS files can play video.

**Comment by orestonce** [comment]
This is a mistake, please retry [version v1.24.2](https://github.com/orestonce/m3u8d/releases/tag/v1.24.2) again.

**Comment by superwushu** [comment]
> This is a mistake, please retry [version v1.24.2](https://github.com/orestonce/m3u8d/releases/tag/v1.24.2) again.

Yeah, working now. Thanks!
