### ISSUE TITLE
能否添加一个配置用于跳过m3u8文件中下载报错的ts块？

### ISSUE THREAD

**Issue by chenyunfei7950** [orestonce/m3u8d#32]
比如一个m3u8中包含几百个ts块，当其中一个ts块指向的url下载失败或404时，跳过该ts对原视频也不会有很大的影响，而不是像现在这样，只要其中一个块报错，整个视频就无法正常自动下载了。

**Comment by chenyunfei7950** [comment]
> 没遇到过这种只出现了一个ts下载失败的情况，这种情况应该算作错误然后停止下载

正常情况一个m3u8文件中所有的ts块都是可以正常下载的，但是我这边遇到了其中的某些ts文件，下载时404，但是在这些ts块之前或之后的都能正常下载，可能是在生成这个m3u8文件时出了什么问题，导致将这些不存在的块添加进去了。

**Comment by orestonce** [comment]
ts编号从1开始，跳过ts的信息用表达式来表示，多段信息用英文逗号分割。例如 `1-10,80,90-100` 就表示跳过编号1到10的ts、并跳过编号为80的ts、并跳过编号为90-100的ts段。怎么样？

**Comment by chenyunfei7950** [comment]
> ts编号从1开始，跳过ts的信息用表达式来表示，多段信息用英文逗号分割。例如 `1-10,80,90-100` 就表示跳过编号1到10的ts、并跳过编号为80的ts、并跳过编号为90-100的ts段。怎么样？

可以的，👍
