### ISSUE TITLE
qt_windows，下载几个视频后会出现线程休眠

### ISSUE THREAD

**Issue by JINGLUODuan** [orestonce/m3u8d#36]
版本：m3u8d_qt_windows_386-v1.24.5.exe
<img width="392" alt="m3u8d_issue01" src="https://github.com/orestonce/m3u8d/assets/140064798/a50ac606-2739-423d-b899-85992c23e67d">
下载几个视频后会出现上图所示的情况，但是等一段时间后，会恢复下载与合并

**Comment by orestonce** [comment]
使用最新的v1.24.6 版本，将“调试日志”、“不删除下载的ts文件” 打开，然后将日志发到本帖看看

**Comment by JINGLUODuan** [comment]
[debuglog.txt](https://github.com/orestonce/m3u8d/files/15427210/debuglog.txt)

**Comment by orestonce** [comment]
我使用你的url下载几次都未出现休眠线程，然后发现你发出的日志的错误原因都是:
````
error2:context deadline exceeded (Client.Timeout or context cancellation while reading body)
````
* 下载ts文件的时候下载超时了，应该是你的电脑的带宽不足，多个线程并发下载的时候有的线程下载速度不足导致。
* 解决办法是升级带宽、降低"下载线程数"、或者忽略此事。
