### ISSUE TITLE
MacOS编译打包失败了

### ISSUE THREAD

**Issue by orestonce** [orestonce/m3u8d#39]
https://github.com/orestonce/m3u8d/actions/runs/9334959235/job/25693794515

**Comment by JasonSanYe** [comment]
没有 MacOS版本了

**Comment by orestonce** [comment]
@JasonSanYe 编译失败导致后续没有这个二进制上传了

**Comment by orestonce** [comment]
最新版已有darwin_arm64_qt版的了，暂无darwin_amd64_qt版的

**Comment by orestonce** [comment]
最新版本已有macos-13编译的darwin_x64和macos14编译的darwin_arm64了
