### ISSUE TITLE
mac的2进制文件下载了打不开

### ISSUE THREAD

**Issue by zhangya4548** [orestonce/m3u8d#4]
mac的2进制文件下载了打不开,尝试了几个版本都是打不开

另外自己下载源码运行,下载到一半提示
go run main.go  download -u https://xlzycdn1.sy-precise.com:65/20220714/0D7sWzwA//3143kb/hls/index.m3u8

<img width="846" alt="image" src="https://user-images.githubusercontent.com/8876518/179998335-ef240e2f-7667-4b16-b06e-7274a4eba0ae.png">

**Comment by orestonce** [comment]
好, 我在本地复现一下这个问题

**Comment by orestonce** [comment]
更新了 1.5.3 版本, 再下载新版试一下呢

**Comment by orestonce** [comment]
mac版本的二进制你是怎么打开的? 只能在命令行下先chmod +x 然后再在命令行环境下运行, mac和linux版本的都是命令行版本.
