### ISSUE TITLE
下载的文件好像没有扩展名呀?

### ISSUE THREAD

**Issue by HahaCodeLife** [orestonce/m3u8d#42]
就是下载的 Mac 的直接是文件名，但是没有扩展名（我说的不是视频文件名而是 github 中你打包提供的下载文件没有扩展名
.zip?）

**Comment by orestonce** [comment]
这是没有扩展名的，是一个普通的可执行文件。

**Comment by orestonce** [comment]
这是没有扩展名的，是一个普通的可执行文件。

**Comment by orestonce** [comment]
和linux的可执行文件一样，chmod +x 然后 ./m3u8d_xxx 就能运行起来
