### ISSUE TITLE
增加设置临时工作目录功能

### ISSUE THREAD

**Issue by Mishasama** [orestonce/m3u8d#45]
这是一个关于机械硬盘的悲伤故事：
当几十GB的ts要合并的时候，如果读写都在同一块物理硬盘上，那速度、磁头、温度的状态都将非常的恶劣。

<details><summary>极端情况</summary>
<p>

![image](https://github.com/user-attachments/assets/a8833f82-7e39-4fd1-958d-0710ef3ff5a4)

</p>
</details> 

![image](https://github.com/user-attachments/assets/a512c6a4-16d8-4cb0-b690-deff6c0416c4)
![image](https://github.com/user-attachments/assets/b76d98c1-12f1-4796-9f61-bc737ac4abb8)
Windows系统和硬盘上的缓存根本不足以应付这种情况。

如果我们能设置一个临时文件夹在硬盘A上用于存放下载的ts文件，而最终合成的mp4的目标文件夹在硬盘B上。这样就能有效分离读写的负荷，提高整个流程的效率了吧？
同时这样也能在目标分区空间不足源文件两倍以上的时候也能顺利完成下载与合并。

**Comment by orestonce** [comment]
最新版本[v1.24.31](https://github.com/orestonce/m3u8d/releases/tag/v1.24.31)已支持设置ts下载目录

**Comment by Mishasama** [comment]
> 最新版本[v1.24.31](https://github.com/orestonce/m3u8d/releases/tag/v1.24.31)已支持设置ts下载目录

Bug: 合并的时候无法像下载那样自动创建不存在的路径对应的文件夹。

**Comment by orestonce** [comment]
> Bug: 合并的时候无法像下载那样自动创建不存在的路径对应的文件夹。

设计如此，合并的时候是不负责创建文件夹的

**Comment by Mishasama** [comment]
> > Bug: 合并的时候无法像下载那样自动创建不存在的路径对应的文件夹。
> 
> 设计如此，合并的时候是不负责创建文件夹的

问题在于引入了更改工作目录后你就不能这样顾头不顾尾了……

**Comment by orestonce** [comment]
没看懂，说详细些

**Comment by Mishasama** [comment]
首先，按照旧版逻辑，即便设置了不存在的目标目录，也会在下载阶段自动创建对应的文件夹，这样路径永远都是有效的。——这是没有毛病的。
但是，按照最新的版本，由于可以分离下载目录与最终合成目标目录。这样原有的在下载阶段自动创建的文件夹就只在下载阶段发挥作用。但是由于最终目标目录没有被创建，所以**在最终合成阶段就会出现目标路径不存在的错误**，导致最终阶段无法完成。

**Comment by orestonce** [comment]
好，以上问题已修复。[v1.24.32](https://github.com/orestonce/m3u8d/releases/tag/v1.24.32) 会自动创建**一层**下载目录、临时目录下的downloading目录，这里只应该创建一层目录。
