### ISSUE TITLE
下载内容花屏

### ISSUE THREAD

**Issue by JessBobby** [orestonce/m3u8d#47]
我下载的视频结果出现卡屏的现象，音视频内容衔接是完整的，但是在播放时，出现包含广告部分就会卡屏。但音频正常，快进后时长也出现跳跃。不清楚是哪一个的问题，另外我在用浏览器猫抓下载后是正常播放的（差异就在原始链接包含广告的部分）。
播放软件：potplayer 240618（1.7.22262） 下载：m3u8d_windows_x86_qt-v1.24.33（包括此前使用过的几个版本）链接：视频网站由猫抓获取的m3u8链接（其中一个：https://vip.ffzy-video.com/20240830/1542_d010396c/index.m3u8 ）
![无标题](https://github.com/user-attachments/assets/c55e9e36-d1a3-4dfa-9323-3c96a3cd4e52)

**Comment by orestonce** [comment]
试试将 “跳过EXT-X-DISCONTINUITY标签包裹的ts” 打勾

**Comment by JessBobby** [comment]
> 试试将 “跳过 EXT-X-DISCONTINUITY 标签包裹的 ts” 打勾

您好，用的还是这个链接测试。结果发现勾选后仍出现该问题。我软件的设置只做了允许不安全的HTTPS请求的设定，其余均为默认。
![image](https://github.com/user-attachments/assets/f2b18f9a-7251-4409-acb9-eaf788772d0c)
我关闭我做的设定后，问题也存在。

**Comment by orestonce** [comment]
这个事情很特殊, m3u8使用 EXT-X-DISCONTINUITY 将ts列表切成70个分区，并且将广告放在了 120-124,455-459 这两段中。
只解决这一个视频的问题，需要将 "跳过ts信息"的表达式编写为 `120-124,455-459`, 并且不要勾选  “跳过 EXT-X-DISCONTINUITY 标签包裹的 ts” 。
* 目前我还没想到好的解决此问题的通用办法

**Comment by JessBobby** [comment]
感谢您的解答！

**Comment by Mishasama** [comment]
> * 目前我还没想到好的解决此问题的通用办法

特殊网站的m3u8就全部下载，让用户启用不删除、不合并，自行进ts文件夹找到广告ts后在界面输入要跳过的编号，再启动合并来重写合并脚本完成合并即可。

**Comment by orestonce** [comment]
> 特殊网站的m3u8就全部下载，让用户启用不删除、不合并，自行进ts文件夹找到广告ts后在界面输入要跳过的编号，再启动合并来重写合并脚本完成合并即可。

* 这样用户很难做，用户需要在几百上千个ts视频中找到10个广告视频，相当于于大海捞针。

**Comment by Mishasama** [comment]
> * 这样用户很难做，用户需要在几百上千个ts视频中找到10个广告视频，相当于于大海捞针。

问题：
1. 程序没有加入AI识别广告画面的功能
2. m3u8文件没有特别的广告插入标识，完全就相当于内嵌的贴片广告，从m3u8上无法判断

方法：
- Windows的资源管理器可以为ts提供有效的预览图，贴片广告画面应该很明显且容易辨别

除非广告ts有什么数据上明显异于正片ts的特征（比如文件尺寸），否则不引入AI很难自动化根治。

**Comment by orestonce** [comment]
@Mishasama @JessBobby 此问题已有通用解决方案，请下载 [v1.25.1](https://github.com/orestonce/m3u8d/releases/tag/v1.25.1)
目前的处理方案是，分析需要合并的ts文件中的第一个文件的分辨率、fps，若后续的ts文件的分辨率、fps与第一个不同则不合并后续的ts文件

**Comment by JessBobby** [comment]
> @Mishasama @JessBobby 此问题已有通用解决方案，请下载 [v1.25.1](https://github.com/orestonce/m3u8d/releases/tag/v1.25.1) 目前的处理方案是，分析需要合并的 ts 文件中的第一个文件的分辨率、fps，若后续的 ts 文件的分辨率、fps 与第一个不同则不合并后续的 ts 文件

我用了这个版本下载跳过了测试链接对应部分。能够成功解决，感谢！
但是请问增加选项：去掉生成的 skip.txt文件吗，可能我在下载电视剧会有大量的m3u8链接下载，这样就会有太多的txt文件，我可能不需要查看它，除非我的视频内容出现缺失

**Comment by orestonce** [comment]
[v1.25.2 改了](https://github.com/orestonce/m3u8d/releases/tag/v1.25.2)，以前是默认直接写 xxx.mp4_skip.txt 日志，现在需要在 “跳过ts信息” 里面编写 "with-skip_log" 才会写这个日志

**Comment by JessBobby** [comment]
> [v1.25.2 改了](https://github.com/orestonce/m3u8d/releases/tag/v1.25.2)，以前是默认直接写 xxx.mp4_skip.txt 日志，现在需要在 “跳过 ts 信息” 里面编写 "with-skip_log" 才会写这个日志

感谢
