### ISSUE TITLE
多线程

### ISSUE THREAD

**Issue by JessBobby** [orestonce/m3u8d#48]
这个问题是和线程相关吗？
我之前默认线程时下载速度大概为10MB/s，后来我改为128线程后，速度为28MB/s上下波动（带宽应该就这么大了）。
    但是在下载快结束时，速度会降到2MB/s，甚至几百kb/s，在进行自动合并前在这会卡30s甚至1分钟。
    只要我在快结束时，点暂停下载再点开始下载就会按照最快速度下载完成剩下内容，再自动进行合并。

**Comment by JessBobby** [comment]
感谢您的解答！

**Comment by Mishasama** [comment]
> 128线程

分块越多并不是越好，很容易导致最后阶段分块太小而无法正常传输数据，进而出现了卡线程的问题。
IDM的32线上限基本上是比较合理的数量了，再小你得想想在最终阶段每一块能不能分到4KB以上。

**Comment by JessBobby** [comment]
> > 128线程
> 
> 分块越多并不是越好，很容易导致最后阶段分块太小而无法正常传输数据，进而出现了卡线程的问题。
> IDM的32线上限基本上是比较合理的数量了，再小你得想想在最终阶段每一块能不能分到4KB以上。

感谢！
