### ISSUE TITLE
log 输出增加下载出错部分汇总

### ISSUE THREAD

**Issue by Mishasama** [orestonce/m3u8d#51]
比如像这样的
<details><summary>debuglog</summary>
<p>

```
===>time: 2024-09-19_17:12:55
get mtime "Sat, 20 Jul 2024 17:23:44 GMT"
===>time: 2024-09-19_17:14:28
http get url "https://d3vd9lfkzbru3h.cloudfront.net/*/chunked/344.ts"
httpReq:
GET /*/chunked/344.ts HTTP/1.1
Host: d3vd9lfkzbru3h.cloudfront.net
Accept: */*
Accept-Encoding: *
Accept-Language: zh-CN,zh;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5
Connection: keep-alive
Referer: https://d3vd9lfkzbru3h.cloudfront.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36


httpResp:
HTTP/1.1 200 OK
Content-Length: 8004288
Accept-Ranges: bytes
Connection: keep-alive
Content-Type: video/MP2T
Date: Thu, 19 Sep 2024 08:01:38 GMT
Etag: "a8a04203bbe17254f4dd62659fb9ab7c"
Last-Modified: Sat, 20 Jul 2024 17:25:04 GMT
Server: AmazonS3
Via: 1.1 9725312341802185c9ebf086bf95544e.cloudfront.net (CloudFront)
X-Amz-Cf-Id: G4p6PcWV4O29i7Cs98qRJWJ_A5PxA20HczN5bwx1evTFE1amse9fTw==
X-Amz-Cf-Pop: SIN2-P2
X-Amz-Server-Side-Encryption: AES256
X-Cache: Miss from cloudfront


time1: 511.6236ms
time4: 13m0.7899238s, bytes: 4643331
error4:context canceled
===>time: 2024-09-19_17:14:28
errMsg 下载ts文件错误: context canceled
```

</p>
</details> 
打开日志后很难去找到哪个ts下载错误了，只能慢慢找就很折磨人了。

能否在下载启动的时候像BT下载那样保留一份种子（m3u8）文件，同时在 log 的最后汇总所有下载错误（丢失）的ts的url及对应的时间码（hh:mm:ss-hh:mm:ss），方便做进一步的处理。

**Comment by paginaweb123** [comment]
install this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by orestonce** [comment]
搜索error就可以搜到了啊，这个就是个详细的调试日志，没必要 搞得很复杂

**Comment by Mishasama** [comment]
![image](https://github.com/user-attachments/assets/feb212a1-a7d9-48a5-9fc3-443825044f8d)
搜不到，实际缺失的并不是就在最末尾的ts记录。

**Comment by orestonce** [comment]
或者搜索 “HTTP/1.1 ”

**Comment by orestonce** [comment]
> 搜不到，实际缺失的并不是就在最末尾的ts记录。

"缺失" 是没有创建ts文件吗，还是是确认被跳过下载了？

**Comment by Mishasama** [comment]
没有创建，在近1000个ts中缺了中间的一个5xx.ts

**Comment by orestonce** [comment]
处理每个ts的时候，记录每个ts的名字、下载url、下载过程、是否跳过的信息就行了。确保每个ts的相关信息都在一起放着就行，需要分析的时候搜索 “00005.ts” 这个字符串就行了

**Comment by Mishasama** [comment]
我的意思是，我们没法高效的发现问题的所在。

1. 我不用肉眼逐个排查序号的话我怎么知道有缺失？具体缺失哪个？
2. 你不汇总我连要在log里搜索什么都不知道。因为不知道是什么问题，哪里出问题。甚至连有没有（发生过）问题也许都不知道（难以察觉）。

**Comment by orestonce** [comment]
* 肉眼排查缺失某一序号是非常简单的，先右键按照文件名排序，然后只关注最右边一列，从上到下每两行之间的序号间隔一定是一致的，不一致则此行丢失了文件。
* 找到丢失了的文件的序号后，只需搜索序号所对应的文件名即可

**Comment by Mishasama** [comment]
> * 肉眼排查缺失某一序号是非常简单的，先右键按照文件名排序，然后只关注最右边一列，从上到下每两行之间的序号间隔一定是一致的，不一致则此行丢失了文件。
> * 找到丢失了的文件的序号后，只需搜索序号所对应的文件名即可


哥……万一是在几千个里面有好几段丢失了好几个ts呢？
之前给你看过的m3u8里就有好多个mute分散在不同的位置了吧？
要不是工作量太大眼睛实在难受我也不想麻烦你😂

**Comment by orestonce** [comment]
那好，我会在下个版本加上此功能。由于最近一两周较忙，下个版本需要在10月才会发布了。

**Comment by Mishasama** [comment]
> 最近一两周较忙

没事，不急，保重！

**Comment by orestonce** [comment]
再确认一下此需求：最终未被写入downloading目录的每一个ts文件，都要收集未写入downloading目录的原因，并将原因按照ts文件的顺序连续写入到日志文件的最后一部分。
格式为：
````
文件名: 00001.ts, 下载url: xxxx, 原因: xxxx, 
文件名: 00002.ts, 下载url: xxxx, 原因: xxxx, 
````

原因包括：
````
1. 触发跳过表达式, xxx
2. http请求错误，xxxx
3. 写入文件错误, xxxx
4. 取消下载
5. ...
````

**Comment by Mishasama** [comment]
格式请改为：

```
（文件名: ）00001.ts
（下载url: ）xxxx
（原因: ）xxxx
（<-- 此处空行 -->）
（文件名: ）00002.ts
（下载url: ）xxxx
（原因: ）xxxx
```

（）括号内内容不要，以便组合第三方脚本进行批处理。


实际效果：
```
---- ERROR TS ----

00001.ts
https://x.xxx/00001.ts
HTTP/403

00002.ts
https://x.xxx/00002.ts
HTTP/403

---- END ----
```

**Comment by orestonce** [comment]
debuglog.txt已汇总ts文件的错误信息：[v1.24.42](https://github.com/orestonce/m3u8d/releases/tag/v1.24.42)
