### ISSUE TITLE
下载ts文件错误 如何解决一下哈

### ISSUE THREAD

**Issue by Xiong-China** [orestonce/m3u8d#53]
![image](https://github.com/user-attachments/assets/51968b57-16d0-4d36-8ceb-f7ed76784394)

**Comment by orestonce** [comment]
有url吗，看起来是下载的ts内容不正确

**Comment by orestonce** [comment]
加密的ts文件的内容的字节数应该是16的整数倍，538808不是16的整数倍所以m3u8d认为内容有问题。
你也可以开启一下“调试日志”，然后将debuglog.txt发出来看看

**Comment by Xiong-China** [comment]
[debuglog.txt](https://github.com/user-attachments/files/17285587/debuglog.txt)

**Comment by orestonce** [comment]
这是是一个bug，涉及到2个暂时无法解决的逻辑错误。临时解决方式是屏蔽：
1. 勾选“跳过 #EXT-X-DISCONTINUITY 标签包裹的ts”
2. 208.ts文件在合并的时候会造成程序崩溃。需要在"跳过ts信息"里写 “208”

**Comment by Xiong-China** [comment]
感谢大神

**Comment by orestonce** [comment]
最新版本已修复此bug，请下载 [v1.25.1](https://github.com/orestonce/m3u8d/releases/tag/v1.25.1)
