### ISSUE TITLE
UA没变

### ISSUE THREAD

**Issue by byteat** [orestonce/m3u8d#54]
m3u8的cURL已经自定义为需要的UA了，但是看请求报头的UA还是Go-http-client/1.1，导致没法嗅探到m3u8资源，这是咋回事，是m3u8文件地址访问的还是默认UA，然后下载m3u8内的视频才是自定义UA吗？

**Comment by orestonce** [comment]
你的curl命令是否解析错了，我写这样可以正确传递UA：
````
curl "http://www.so.com:8080/" \
 -H 'Cache-Control: max-age=0' \
 -H 'Connection: keep-alive' \
 -H 'Sec-Fetch-Mode: navigate' \
 -H 'Sec-Fetch-Site: same-site' \
 -H 'User-Agent: M36' \
 -H 'Referer: https://wenda.so.com/' \
 -H 'Sec-Ch-Ua-Mobile: ?0' \
 -H 'Sec-Fetch-Dest: iframe' \
 -H 'Upgrade-Insecure-Requests: 1' \
 -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
 -H 'Accept-Language: zh-CN,zh;q=0.9' \
 -H 'Content-Type: application/x-www-form-urlencoded' \
 -H 'Origin: https://wenda.so.com'
````

**Comment by byteat** [comment]
curl 'xxx.xxx/xxx' \
-X 'GET' \
-H 'Accept: */*' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'Cookie: device=241009fainrh22' \
-H 'Connection: Keep-Alive' \
-H 'Sec-Fetch-Mode: no-cors' \
-H 'Host: xxx.xxx' \
-H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1' \
-H 'Accept-Language: zh-CN,zh-Hans;q=0.9' \
-H 'Accept-Encoding: gzip' \
-H 'Sec-Fetch-Dest: video' \
-H 'X-Playback-Session-Id: 57C00E63-E1D3-4BB6-9C34-2466F739E59B'
这样的应该没问题才对啊

**Comment by orestonce** [comment]
嗯，应该没问题的。
你开启"调试日志"，然后把调试信息发出来看看呢

**Comment by orestonce** [comment]
如果有涉及cookie的敏感信息，可发送邮件到 orestonce#163.com

**Comment by orestonce** [comment]
这是我在服务端监听数据得到的请求，请求m3u8时候的http头信息是正确传递了UA的
````
root@iZ2vc22wouemzv8ppoymkoZ:~# nc -l 8080
GET /user1 HTTP/1.1
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1
Accept: /
Accept-Encoding: gzip
Accept-Language: zh-CN,zh-Hans;q=0.9
Connection: Keep-Alive
Cookie: device=241009fainrh22
Sec-Fetch-Dest: video
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
X-Playback-Session-Id: 57C00E63-E1D3-4BB6-9C34-2466F739E59B
````

**Comment by byteat** [comment]
已发邮件😏
