### ISSUE TITLE
v1.25.2 功能位置逻辑似乎有点问题

### ISSUE THREAD

**Issue by Mishasama** [orestonce/m3u8d#55]
https://github.com/orestonce/m3u8d/releases/tag/v1.25.2
![image](https://github.com/user-attachments/assets/08e2d4dd-a987-4a0b-af93-c04a10ec5515)
你这也不是跳过的条件参数啊……它并不参与到实际的跳过操作。
把它放到下面的日志选项旁边就好了，也方便理解。

**Comment by orestonce** [comment]
也行，这个没仔细考虑，很随意
