### ISSUE TITLE
[疑问] QT的启动路径与设置保存有关联？

### ISSUE THREAD

**Issue by Mishasama** [orestonce/m3u8d#56]
想问这个问题很久了……

举个例子：

1. 我使用explorer打开m3u8d，然后设置好各种参数，比如16线程。接着关闭程序。
2. 然后又再用Xplorer打开m3u8d，发现设置恢复到初始状态。再次设置为另外一组设置，比如32线程。接着关闭程序。
3. 接着再用explorer打开m3u8d，发现设置是16线程的那套。不做修改，关闭程序。
4. 再用Xplorer打开m3u8d，发现设置是32线程的那套。

问题：

1. 这是故意这么设计的吗？
2. 可以固定无论从哪里，用什么启动程序都是保存和读取在同一个位置里的吗？
3. 我好像没发现配置文件，那这样设计的话不会很浪费注册表吗？

**Comment by orestonce** [comment]
* 启动后会定时将设置信息保存在**启动目录下的m3u8d_config.json 文件**中
* 点击右上角的x关闭m3u8d-qt的时候会保存一次最新配置
* 此处保存逻辑未作多进程管控，如果在同一目录启动多个m3u8d-qt进程，每个进程都会用自己的保存周期定时写入m3u8d_config.json
* 你描述的例子，根据我的推测，第3/4步的效果应该都是32线程的那套（第三次启动，读取第二次启动的配置信息）

## 问题解答
1. 是故意如此设计的，我认为这个配置信息承担的功能只是保存最新的一份配置，没必要搞得很复杂，所以也未做多进程并发、差异写入、变更后才写入等措施，而是直接定时无条件写入。
2. 不能固定在某个位置，原因一是删除m3u8d-qt的时候不方便删；原因二是如果多个启动目录分别启动m3u8d-qt进程，则可以分别保存多份配置信息。
3. 配置文件在 启动目录下的m3u8d_config.json 文件

**Comment by Mishasama** [comment]
> 不能固定在某个位置，原因一是删除m3u8d-qt的时候不方便删；原因二是如果多个启动目录分别启动m3u8d-qt进程，则可以分别保存多份配置信息。

不知道是不是我误解了你的意思。
为什么不能直接把配置文件放在m3u8d主程序的exe的旁边？而是在启动器（如explorer.exe）的目录里？
这一与二不矛盾吗？

我已经很多年没见到过这种设计了……感觉回到了win98的时代😂

**Comment by orestonce** [comment]
不是在explorer所在目录，而是启动时候的工作目录。如果你是在文件管理器里面双击启动m3u8d-qt程序，那么就在m3u8d-qt程序所在的目录下。

**Comment by Mishasama** [comment]
但是我用其它程序来启动它的话就不会在qt的目录下了

**Comment by orestonce** [comment]
已更改为exe所在目录，跟启动时的工作目录无关了
