### ISSUE TITLE
目测未支持多线程下载，希望增加

### ISSUE THREAD

**Issue by Darling-Lee** [orestonce/m3u8d#6]
下载速度贼慢，远不及主流资源嗅探多线程下载器配合网页m3u播放器来得实际，希望增加多线程下载的功能

**Comment by orestonce** [comment]
sorry, 这是个bug https://github.com/orestonce/m3u8d/blob/a46b8388c7dfe8046807580dc154a97297f4ed68/download.go#L451
有多线程支持的, 有一次调试的时候改成了单线程, 马上修复一下

**Comment by orestonce** [comment]
最新版已开启多线程
