### ISSUE TITLE
无效的HTTP状态码：499

### ISSUE THREAD

**Issue by WeiZixu-HIT** [orestonce/m3u8d#60]
PS D:\下载\edge下载\videodownload> .\m3u8d.exe download -u https://vip.lzcdn2.com/20220511/6151_e379b948/index.m3u8
下载进度                                                      0.00%55%
下载ts文件错误: 00337.ts: invalid http status code: 499 url: https://vip.lzcdn2.com/20220511/6151_e379b948/1200k/hls/6c38e2dfb23000330.ts

**Comment by orestonce** [comment]
我复现了，但是报499错误在280.ts。看起来是服务端限制了，尝试使用少一些的线程下载视频、或者过一会再下载。
`--ThreadCount 1`
