### ISSUE TITLE
关于增加AES 常规解密功能

### ISSUE THREAD

**Issue by zxc1dai** [orestonce/m3u8d#7]
能否增加AES 常规解密功能，谢谢。

**Comment by orestonce** [comment]
有相关的解密逻辑，https://github.com/orestonce/m3u8d/blob/main/download.go#L414
你的哪个url无法下载吗？

**Comment by zxc1dai** [comment]
tver.jp和tv-tokyo.co.jp上用m3u8-download嗅探出来的m3u8地址总是报地址错误，无法下载。

**Comment by orestonce** [comment]
好
