### ISSUE TITLE
能否添加非标m3u8格式下载呢？

### ISSUE THREAD

**Issue by yyxiaofeng** [orestonce/m3u8d#8]
现在国外好多IPTV直播都采用非标m3u8格式，例如 http://8amigg.top:80/aq68/85df6s5df/236，能否添加该类型格式下载呢？

**Comment by orestonce** [comment]
这是什么数据？

**Comment by yyxiaofeng** [comment]
这个没有播放网页，就是这样的格式，用VLC或者Potplay播放，https://github.com/mcleisson/m3u/blob/main/lista_completa2.m3u
https://github.com/muhaift/m3u/blob/main/MyPlay
一般来说[http://8amigg.top:80]是地址，用户名=[aq68]，密码=[85df6s5df]，频道号=236

**Comment by orestonce** [comment]
看了一下，这个下载一时半会做不出来

**Comment by yyxiaofeng** [comment]
好吧，还是感谢
